server:
  port: 8090

spring:
  sql:
    init:
      schema-locations:
      - classpath:/data/hsqldb/schema.sql
      data-locations:
      - classpath:/data/hsqldb/data.sql
  jpa:
    hibernate:
      ddl-auto:  update
logging:
  level:
    org:
      springframework:
        security: DEBUG
    
    